name: HeightBorder
version: ${project.version}
main: me.zorua162.heightborder.HeightBorder
api-version: 1.19
depend: [WorldBorderAPI]
commands:
  heightborder:
    description: The main height border comand
    usage: /<command> <subcommands>
    permission: world-border.command.heightborder
    aliases: ["hb"]
