name: HeightBorder
version: ${project.version}
main: me.zorua162.heightborder.HeightBorder
api-version: 1.19
depend: [WorldBorderAPI]
commands:
  heightborder:
    description: The main height border comand
    usage: /<command> <subcommands>
    permission: world-border.command.heightborder
    aliases: ["hb"]
  toggledisplay:
    description: toggle whether the borders distance is displayed in the action bar
    usage: /toggledisplay
    permission: world-border.command.toggledisplay
    aliases: ["td"]
